// containers
#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <queue>
#include <set>
#include <span>
#include <stack>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// misc
#include <cassert>
#include <chrono>
#include <filesystem>
#include <functional>
#include <iterator>
#include <memory>
#include <optional>
#include <stdexcept>
#include <thread>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>

// thirdparty
#include <boost/asio.hpp>
#include <msgpack.hpp>
#include <range/v3/all.hpp>
#include <spdlog/spdlog.h>
